/*
 * Cisco Intersight
 *
 * Cisco Intersight is a management platform delivered as a service with embedded analytics for your Cisco and 3rd party IT infrastructure. This platform offers an intelligent level of management that enables IT organizations to analyze, simplify, and automate their environments in more advanced ways than the prior generations of tools. Cisco Intersight provides an integrated and intuitive management experience for resources in the traditional data center as well as at the edge. With flexible deployment options to address complex security needs, getting started with Intersight is quick and easy. Cisco Intersight has deep integration with Cisco UCS and HyperFlex systems allowing for remote deployment, configuration, and ongoing maintenance. The model-based deployment works for a single system in a remote location or hundreds of systems in a data center and enables rapid, standardized configuration and deployment. It also streamlines maintaining those systems whether you are working with small or very large configurations. The Intersight OpenAPI document defines the complete set of properties that are returned in the HTTP response. From that perspective, a client can expect that no additional properties are returned, unless these properties are explicitly defined in the OpenAPI document. However, when a client uses an older version of the Intersight OpenAPI document, the server may send additional properties because the software is more recent than the client. In that case, the client may receive properties that it does not know about. Some generated SDKs perform a strict validation of the HTTP response body against the OpenAPI document. This document was created on 2020-06-13T05:58:55-07:00.
 *
 * API version: 1.0.9-1855
 * Contact: intersight@cisco.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package intersight

import (
	"encoding/json"
	"fmt"
)

// TelemetryDruidPostAggregator - struct for TelemetryDruidPostAggregator
type TelemetryDruidPostAggregator struct {
	TelemetryDruidArithmeticPostAggregator            *TelemetryDruidArithmeticPostAggregator
	TelemetryDruidConstantPostAggregator              *TelemetryDruidConstantPostAggregator
	TelemetryDruidFieldAccessorPostAggregator         *TelemetryDruidFieldAccessorPostAggregator
	TelemetryDruidGreatestLeastPostAggregator         *TelemetryDruidGreatestLeastPostAggregator
	TelemetryDruidHyperUniquePostAggregator           *TelemetryDruidHyperUniquePostAggregator
	TelemetryDruidThetaSketchEstimatePostAggregator   *TelemetryDruidThetaSketchEstimatePostAggregator
	TelemetryDruidThetaSketchOperationsPostAggregator *TelemetryDruidThetaSketchOperationsPostAggregator
}

// TelemetryDruidArithmeticPostAggregatorAsTelemetryDruidPostAggregator is a convenience function that returns TelemetryDruidArithmeticPostAggregator wrapped in TelemetryDruidPostAggregator
func TelemetryDruidArithmeticPostAggregatorAsTelemetryDruidPostAggregator(v *TelemetryDruidArithmeticPostAggregator) TelemetryDruidPostAggregator {
	return TelemetryDruidPostAggregator{TelemetryDruidArithmeticPostAggregator: v}
}

// TelemetryDruidConstantPostAggregatorAsTelemetryDruidPostAggregator is a convenience function that returns TelemetryDruidConstantPostAggregator wrapped in TelemetryDruidPostAggregator
func TelemetryDruidConstantPostAggregatorAsTelemetryDruidPostAggregator(v *TelemetryDruidConstantPostAggregator) TelemetryDruidPostAggregator {
	return TelemetryDruidPostAggregator{TelemetryDruidConstantPostAggregator: v}
}

// TelemetryDruidFieldAccessorPostAggregatorAsTelemetryDruidPostAggregator is a convenience function that returns TelemetryDruidFieldAccessorPostAggregator wrapped in TelemetryDruidPostAggregator
func TelemetryDruidFieldAccessorPostAggregatorAsTelemetryDruidPostAggregator(v *TelemetryDruidFieldAccessorPostAggregator) TelemetryDruidPostAggregator {
	return TelemetryDruidPostAggregator{TelemetryDruidFieldAccessorPostAggregator: v}
}

// TelemetryDruidGreatestLeastPostAggregatorAsTelemetryDruidPostAggregator is a convenience function that returns TelemetryDruidGreatestLeastPostAggregator wrapped in TelemetryDruidPostAggregator
func TelemetryDruidGreatestLeastPostAggregatorAsTelemetryDruidPostAggregator(v *TelemetryDruidGreatestLeastPostAggregator) TelemetryDruidPostAggregator {
	return TelemetryDruidPostAggregator{TelemetryDruidGreatestLeastPostAggregator: v}
}

// TelemetryDruidHyperUniquePostAggregatorAsTelemetryDruidPostAggregator is a convenience function that returns TelemetryDruidHyperUniquePostAggregator wrapped in TelemetryDruidPostAggregator
func TelemetryDruidHyperUniquePostAggregatorAsTelemetryDruidPostAggregator(v *TelemetryDruidHyperUniquePostAggregator) TelemetryDruidPostAggregator {
	return TelemetryDruidPostAggregator{TelemetryDruidHyperUniquePostAggregator: v}
}

// TelemetryDruidThetaSketchEstimatePostAggregatorAsTelemetryDruidPostAggregator is a convenience function that returns TelemetryDruidThetaSketchEstimatePostAggregator wrapped in TelemetryDruidPostAggregator
func TelemetryDruidThetaSketchEstimatePostAggregatorAsTelemetryDruidPostAggregator(v *TelemetryDruidThetaSketchEstimatePostAggregator) TelemetryDruidPostAggregator {
	return TelemetryDruidPostAggregator{TelemetryDruidThetaSketchEstimatePostAggregator: v}
}

// TelemetryDruidThetaSketchOperationsPostAggregatorAsTelemetryDruidPostAggregator is a convenience function that returns TelemetryDruidThetaSketchOperationsPostAggregator wrapped in TelemetryDruidPostAggregator
func TelemetryDruidThetaSketchOperationsPostAggregatorAsTelemetryDruidPostAggregator(v *TelemetryDruidThetaSketchOperationsPostAggregator) TelemetryDruidPostAggregator {
	return TelemetryDruidPostAggregator{TelemetryDruidThetaSketchOperationsPostAggregator: v}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *TelemetryDruidPostAggregator) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into TelemetryDruidArithmeticPostAggregator
	err = json.Unmarshal(data, &dst.TelemetryDruidArithmeticPostAggregator)
	if err == nil {
		jsonTelemetryDruidArithmeticPostAggregator, _ := json.Marshal(dst.TelemetryDruidArithmeticPostAggregator)
		if string(jsonTelemetryDruidArithmeticPostAggregator) == "{}" { // empty struct
			dst.TelemetryDruidArithmeticPostAggregator = nil
		} else {
			match++
		}
	} else {
		dst.TelemetryDruidArithmeticPostAggregator = nil
	}

	// try to unmarshal data into TelemetryDruidConstantPostAggregator
	err = json.Unmarshal(data, &dst.TelemetryDruidConstantPostAggregator)
	if err == nil {
		jsonTelemetryDruidConstantPostAggregator, _ := json.Marshal(dst.TelemetryDruidConstantPostAggregator)
		if string(jsonTelemetryDruidConstantPostAggregator) == "{}" { // empty struct
			dst.TelemetryDruidConstantPostAggregator = nil
		} else {
			match++
		}
	} else {
		dst.TelemetryDruidConstantPostAggregator = nil
	}

	// try to unmarshal data into TelemetryDruidFieldAccessorPostAggregator
	err = json.Unmarshal(data, &dst.TelemetryDruidFieldAccessorPostAggregator)
	if err == nil {
		jsonTelemetryDruidFieldAccessorPostAggregator, _ := json.Marshal(dst.TelemetryDruidFieldAccessorPostAggregator)
		if string(jsonTelemetryDruidFieldAccessorPostAggregator) == "{}" { // empty struct
			dst.TelemetryDruidFieldAccessorPostAggregator = nil
		} else {
			match++
		}
	} else {
		dst.TelemetryDruidFieldAccessorPostAggregator = nil
	}

	// try to unmarshal data into TelemetryDruidGreatestLeastPostAggregator
	err = json.Unmarshal(data, &dst.TelemetryDruidGreatestLeastPostAggregator)
	if err == nil {
		jsonTelemetryDruidGreatestLeastPostAggregator, _ := json.Marshal(dst.TelemetryDruidGreatestLeastPostAggregator)
		if string(jsonTelemetryDruidGreatestLeastPostAggregator) == "{}" { // empty struct
			dst.TelemetryDruidGreatestLeastPostAggregator = nil
		} else {
			match++
		}
	} else {
		dst.TelemetryDruidGreatestLeastPostAggregator = nil
	}

	// try to unmarshal data into TelemetryDruidHyperUniquePostAggregator
	err = json.Unmarshal(data, &dst.TelemetryDruidHyperUniquePostAggregator)
	if err == nil {
		jsonTelemetryDruidHyperUniquePostAggregator, _ := json.Marshal(dst.TelemetryDruidHyperUniquePostAggregator)
		if string(jsonTelemetryDruidHyperUniquePostAggregator) == "{}" { // empty struct
			dst.TelemetryDruidHyperUniquePostAggregator = nil
		} else {
			match++
		}
	} else {
		dst.TelemetryDruidHyperUniquePostAggregator = nil
	}

	// try to unmarshal data into TelemetryDruidThetaSketchEstimatePostAggregator
	err = json.Unmarshal(data, &dst.TelemetryDruidThetaSketchEstimatePostAggregator)
	if err == nil {
		jsonTelemetryDruidThetaSketchEstimatePostAggregator, _ := json.Marshal(dst.TelemetryDruidThetaSketchEstimatePostAggregator)
		if string(jsonTelemetryDruidThetaSketchEstimatePostAggregator) == "{}" { // empty struct
			dst.TelemetryDruidThetaSketchEstimatePostAggregator = nil
		} else {
			match++
		}
	} else {
		dst.TelemetryDruidThetaSketchEstimatePostAggregator = nil
	}

	// try to unmarshal data into TelemetryDruidThetaSketchOperationsPostAggregator
	err = json.Unmarshal(data, &dst.TelemetryDruidThetaSketchOperationsPostAggregator)
	if err == nil {
		jsonTelemetryDruidThetaSketchOperationsPostAggregator, _ := json.Marshal(dst.TelemetryDruidThetaSketchOperationsPostAggregator)
		if string(jsonTelemetryDruidThetaSketchOperationsPostAggregator) == "{}" { // empty struct
			dst.TelemetryDruidThetaSketchOperationsPostAggregator = nil
		} else {
			match++
		}
	} else {
		dst.TelemetryDruidThetaSketchOperationsPostAggregator = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.TelemetryDruidArithmeticPostAggregator = nil
		dst.TelemetryDruidConstantPostAggregator = nil
		dst.TelemetryDruidFieldAccessorPostAggregator = nil
		dst.TelemetryDruidGreatestLeastPostAggregator = nil
		dst.TelemetryDruidHyperUniquePostAggregator = nil
		dst.TelemetryDruidThetaSketchEstimatePostAggregator = nil
		dst.TelemetryDruidThetaSketchOperationsPostAggregator = nil

		return fmt.Errorf("Data matches more than one schema in oneOf(TelemetryDruidPostAggregator)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("Data failed to match schemas in oneOf(TelemetryDruidPostAggregator)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src TelemetryDruidPostAggregator) MarshalJSON() ([]byte, error) {
	if src.TelemetryDruidArithmeticPostAggregator != nil {
		return json.Marshal(&src.TelemetryDruidArithmeticPostAggregator)
	}

	if src.TelemetryDruidConstantPostAggregator != nil {
		return json.Marshal(&src.TelemetryDruidConstantPostAggregator)
	}

	if src.TelemetryDruidFieldAccessorPostAggregator != nil {
		return json.Marshal(&src.TelemetryDruidFieldAccessorPostAggregator)
	}

	if src.TelemetryDruidGreatestLeastPostAggregator != nil {
		return json.Marshal(&src.TelemetryDruidGreatestLeastPostAggregator)
	}

	if src.TelemetryDruidHyperUniquePostAggregator != nil {
		return json.Marshal(&src.TelemetryDruidHyperUniquePostAggregator)
	}

	if src.TelemetryDruidThetaSketchEstimatePostAggregator != nil {
		return json.Marshal(&src.TelemetryDruidThetaSketchEstimatePostAggregator)
	}

	if src.TelemetryDruidThetaSketchOperationsPostAggregator != nil {
		return json.Marshal(&src.TelemetryDruidThetaSketchOperationsPostAggregator)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *TelemetryDruidPostAggregator) GetActualInstance() interface{} {
	if obj.TelemetryDruidArithmeticPostAggregator != nil {
		return obj.TelemetryDruidArithmeticPostAggregator
	}

	if obj.TelemetryDruidConstantPostAggregator != nil {
		return obj.TelemetryDruidConstantPostAggregator
	}

	if obj.TelemetryDruidFieldAccessorPostAggregator != nil {
		return obj.TelemetryDruidFieldAccessorPostAggregator
	}

	if obj.TelemetryDruidGreatestLeastPostAggregator != nil {
		return obj.TelemetryDruidGreatestLeastPostAggregator
	}

	if obj.TelemetryDruidHyperUniquePostAggregator != nil {
		return obj.TelemetryDruidHyperUniquePostAggregator
	}

	if obj.TelemetryDruidThetaSketchEstimatePostAggregator != nil {
		return obj.TelemetryDruidThetaSketchEstimatePostAggregator
	}

	if obj.TelemetryDruidThetaSketchOperationsPostAggregator != nil {
		return obj.TelemetryDruidThetaSketchOperationsPostAggregator
	}

	// all schemas are nil
	return nil
}

type NullableTelemetryDruidPostAggregator struct {
	value *TelemetryDruidPostAggregator
	isSet bool
}

func (v NullableTelemetryDruidPostAggregator) Get() *TelemetryDruidPostAggregator {
	return v.value
}

func (v *NullableTelemetryDruidPostAggregator) Set(val *TelemetryDruidPostAggregator) {
	v.value = val
	v.isSet = true
}

func (v NullableTelemetryDruidPostAggregator) IsSet() bool {
	return v.isSet
}

func (v *NullableTelemetryDruidPostAggregator) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTelemetryDruidPostAggregator(val *TelemetryDruidPostAggregator) *NullableTelemetryDruidPostAggregator {
	return &NullableTelemetryDruidPostAggregator{value: val, isSet: true}
}

func (v NullableTelemetryDruidPostAggregator) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTelemetryDruidPostAggregator) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
