// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AssetWorkloadOptimizerService Asset:Workload Optimizer Service
//
// WorkloadOptimizerService provides the necessary configuration details to enable Intersight Workflow Optimizer on the selected managed target. Subject to licensing.
//
// swagger:model assetWorkloadOptimizerService
type AssetWorkloadOptimizerService struct {
	AssetService

	AssetWorkloadOptimizerServiceAllOf1
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *AssetWorkloadOptimizerService) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 AssetService
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.AssetService = aO0

	// AO1
	var aO1 AssetWorkloadOptimizerServiceAllOf1
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.AssetWorkloadOptimizerServiceAllOf1 = aO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m AssetWorkloadOptimizerService) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.AssetService)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.AssetWorkloadOptimizerServiceAllOf1)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this asset workload optimizer service
func (m *AssetWorkloadOptimizerService) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with AssetService
	if err := m.AssetService.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with AssetWorkloadOptimizerServiceAllOf1

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *AssetWorkloadOptimizerService) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AssetWorkloadOptimizerService) UnmarshalBinary(b []byte) error {
	var res AssetWorkloadOptimizerService
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// AssetWorkloadOptimizerServiceAllOf1 asset workload optimizer service all of1
//
// swagger:model AssetWorkloadOptimizerServiceAllOf1
type AssetWorkloadOptimizerServiceAllOf1 interface{}
