// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BootLocalDisk Local Disk
//
// Device type used when booting from a local disk device.
//
// swagger:model bootLocalDisk
type BootLocalDisk struct {
	BootDeviceBase

	// Details of the bootloader to be used during boot from local disk.
	Bootloader *BootBootloader `json:"Bootloader,omitempty"`

	// The slot id of the local disk device. Supported values are (1-255, "M", "HBA", "SAS", "RAID", "MRAID", "MSTOR-RAID").
	Slot string `json:"Slot,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *BootLocalDisk) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 BootDeviceBase
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.BootDeviceBase = aO0

	// AO1
	var dataAO1 struct {
		Bootloader *BootBootloader `json:"Bootloader,omitempty"`

		Slot string `json:"Slot,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.Bootloader = dataAO1.Bootloader

	m.Slot = dataAO1.Slot

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m BootLocalDisk) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.BootDeviceBase)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	var dataAO1 struct {
		Bootloader *BootBootloader `json:"Bootloader,omitempty"`

		Slot string `json:"Slot,omitempty"`
	}

	dataAO1.Bootloader = m.Bootloader

	dataAO1.Slot = m.Slot

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this boot local disk
func (m *BootLocalDisk) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with BootDeviceBase
	if err := m.BootDeviceBase.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBootloader(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BootLocalDisk) validateBootloader(formats strfmt.Registry) error {

	if swag.IsZero(m.Bootloader) { // not required
		return nil
	}

	if m.Bootloader != nil {
		if err := m.Bootloader.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Bootloader")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *BootLocalDisk) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BootLocalDisk) UnmarshalBinary(b []byte) error {
	var res BootLocalDisk
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
