// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// DevopsAbstractTriggerDetails Devops:Abstract Trigger Details
//
// AbstractTriggerDetails is a base abstract type that describes specific actions which devops users can perform within a micro service.
// The actions are often remediations for bugs. For example, processing of a notification may fail because of a defect. Once the bug is fixed, it may be necessary to reprocess the notification to recover any missed state changes. The subtype NotificationTrigger implements such a capability.
//
// swagger:model devopsAbstractTriggerDetails
type DevopsAbstractTriggerDetails struct {
	DevopsAbstractTriggerDetailsAO0P0
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *DevopsAbstractTriggerDetails) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 DevopsAbstractTriggerDetailsAO0P0
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.DevopsAbstractTriggerDetailsAO0P0 = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m DevopsAbstractTriggerDetails) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.DevopsAbstractTriggerDetailsAO0P0)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this devops abstract trigger details
func (m *DevopsAbstractTriggerDetails) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with DevopsAbstractTriggerDetailsAO0P0
	if err := m.DevopsAbstractTriggerDetailsAO0P0.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *DevopsAbstractTriggerDetails) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DevopsAbstractTriggerDetails) UnmarshalBinary(b []byte) error {
	var res DevopsAbstractTriggerDetails
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// DevopsAbstractTriggerDetailsAO0P0 devops abstract trigger details a o0 p0
// swagger:model DevopsAbstractTriggerDetailsAO0P0
type DevopsAbstractTriggerDetailsAO0P0 struct {

	// The concrete type of this complex type.
	//
	// The ObjectType property must be set explicitly by API clients when the type is ambiguous. In all other cases, the
	// ObjectType is optional.
	// The type is ambiguous when a managed object contains an array of nested documents, and the documents in the array
	// are heterogeneous, i.e. the array can contain nested documents of different types.
	//
	//
	ObjectType string `json:"ObjectType,omitempty"`

	// devops abstract trigger details a o0 p0
	DevopsAbstractTriggerDetailsAO0P0 map[string]interface{} `json:"-"`
}

// UnmarshalJSON unmarshals this object with additional properties from JSON
func (m *DevopsAbstractTriggerDetailsAO0P0) UnmarshalJSON(data []byte) error {
	// stage 1, bind the properties
	var stage1 struct {

		// The concrete type of this complex type.
		//
		// The ObjectType property must be set explicitly by API clients when the type is ambiguous. In all other cases, the
		// ObjectType is optional.
		// The type is ambiguous when a managed object contains an array of nested documents, and the documents in the array
		// are heterogeneous, i.e. the array can contain nested documents of different types.
		//
		//
		ObjectType string `json:"ObjectType,omitempty"`
	}
	if err := json.Unmarshal(data, &stage1); err != nil {
		return err
	}
	var rcv DevopsAbstractTriggerDetailsAO0P0

	rcv.ObjectType = stage1.ObjectType

	*m = rcv

	// stage 2, remove properties and add to map
	stage2 := make(map[string]json.RawMessage)
	if err := json.Unmarshal(data, &stage2); err != nil {
		return err
	}

	delete(stage2, "ObjectType")

	// stage 3, add additional properties values
	if len(stage2) > 0 {
		result := make(map[string]interface{})
		for k, v := range stage2 {
			var toadd interface{}
			if err := json.Unmarshal(v, &toadd); err != nil {
				return err
			}
			result[k] = toadd
		}
		m.DevopsAbstractTriggerDetailsAO0P0 = result
	}

	return nil
}

// MarshalJSON marshals this object with additional properties into a JSON object
func (m DevopsAbstractTriggerDetailsAO0P0) MarshalJSON() ([]byte, error) {
	var stage1 struct {

		// The concrete type of this complex type.
		//
		// The ObjectType property must be set explicitly by API clients when the type is ambiguous. In all other cases, the
		// ObjectType is optional.
		// The type is ambiguous when a managed object contains an array of nested documents, and the documents in the array
		// are heterogeneous, i.e. the array can contain nested documents of different types.
		//
		//
		ObjectType string `json:"ObjectType,omitempty"`
	}

	stage1.ObjectType = m.ObjectType

	// make JSON object for known properties
	props, err := json.Marshal(stage1)
	if err != nil {
		return nil, err
	}

	if len(m.DevopsAbstractTriggerDetailsAO0P0) == 0 {
		return props, nil
	}

	// make JSON object for the additional properties
	additional, err := json.Marshal(m.DevopsAbstractTriggerDetailsAO0P0)
	if err != nil {
		return nil, err
	}

	if len(props) < 3 {
		return additional, nil
	}

	// concatenate the 2 objects
	props[len(props)-1] = ','
	return append(props, additional[1:]...), nil
}

// Validate validates this devops abstract trigger details a o0 p0
func (m *DevopsAbstractTriggerDetailsAO0P0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DevopsAbstractTriggerDetailsAO0P0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DevopsAbstractTriggerDetailsAO0P0) UnmarshalBinary(b []byte) error {
	var res DevopsAbstractTriggerDetailsAO0P0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
