// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// HyperflexStPlatformClusterHealingInfo Hyperflex:St Platform Cluster Healing Info
// swagger:model hyperflexStPlatformClusterHealingInfo
type HyperflexStPlatformClusterHealingInfo struct {
	MoBaseComplexType

	HyperflexStPlatformClusterHealingInfoAO1P1
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *HyperflexStPlatformClusterHealingInfo) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 MoBaseComplexType
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.MoBaseComplexType = aO0

	// AO1
	var aO1 HyperflexStPlatformClusterHealingInfoAO1P1
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.HyperflexStPlatformClusterHealingInfoAO1P1 = aO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m HyperflexStPlatformClusterHealingInfo) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.MoBaseComplexType)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.HyperflexStPlatformClusterHealingInfoAO1P1)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this hyperflex st platform cluster healing info
func (m *HyperflexStPlatformClusterHealingInfo) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with MoBaseComplexType
	if err := m.MoBaseComplexType.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with HyperflexStPlatformClusterHealingInfoAO1P1
	if err := m.HyperflexStPlatformClusterHealingInfoAO1P1.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *HyperflexStPlatformClusterHealingInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HyperflexStPlatformClusterHealingInfo) UnmarshalBinary(b []byte) error {
	var res HyperflexStPlatformClusterHealingInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// HyperflexStPlatformClusterHealingInfoAO1P1 hyperflex st platform cluster healing info a o1 p1
// swagger:model HyperflexStPlatformClusterHealingInfoAO1P1
type HyperflexStPlatformClusterHealingInfoAO1P1 struct {

	// estimated completion time in seconds
	// Read Only: true
	EstimatedCompletionTimeInSeconds int64 `json:"EstimatedCompletionTimeInSeconds,omitempty"`

	// in progress
	// Read Only: true
	InProgress *bool `json:"InProgress,omitempty"`

	// messages
	// Read Only: true
	Messages []string `json:"Messages"`

	// messages iterator
	// Read Only: true
	MessagesIterator interface{} `json:"MessagesIterator,omitempty"`

	// messages size
	// Read Only: true
	MessagesSize int64 `json:"MessagesSize,omitempty"`

	// percent complete
	// Read Only: true
	PercentComplete int64 `json:"PercentComplete,omitempty"`

	// hyperflex st platform cluster healing info a o1 p1
	HyperflexStPlatformClusterHealingInfoAO1P1 map[string]interface{} `json:"-"`
}

// UnmarshalJSON unmarshals this object with additional properties from JSON
func (m *HyperflexStPlatformClusterHealingInfoAO1P1) UnmarshalJSON(data []byte) error {
	// stage 1, bind the properties
	var stage1 struct {

		// estimated completion time in seconds
		// Read Only: true
		EstimatedCompletionTimeInSeconds int64 `json:"EstimatedCompletionTimeInSeconds,omitempty"`

		// in progress
		// Read Only: true
		InProgress *bool `json:"InProgress,omitempty"`

		// messages
		// Read Only: true
		Messages []string `json:"Messages"`

		// messages iterator
		// Read Only: true
		MessagesIterator interface{} `json:"MessagesIterator,omitempty"`

		// messages size
		// Read Only: true
		MessagesSize int64 `json:"MessagesSize,omitempty"`

		// percent complete
		// Read Only: true
		PercentComplete int64 `json:"PercentComplete,omitempty"`
	}
	if err := json.Unmarshal(data, &stage1); err != nil {
		return err
	}
	var rcv HyperflexStPlatformClusterHealingInfoAO1P1

	rcv.EstimatedCompletionTimeInSeconds = stage1.EstimatedCompletionTimeInSeconds

	rcv.InProgress = stage1.InProgress

	rcv.Messages = stage1.Messages

	rcv.MessagesIterator = stage1.MessagesIterator

	rcv.MessagesSize = stage1.MessagesSize

	rcv.PercentComplete = stage1.PercentComplete

	*m = rcv

	// stage 2, remove properties and add to map
	stage2 := make(map[string]json.RawMessage)
	if err := json.Unmarshal(data, &stage2); err != nil {
		return err
	}

	delete(stage2, "EstimatedCompletionTimeInSeconds")

	delete(stage2, "InProgress")

	delete(stage2, "Messages")

	delete(stage2, "MessagesIterator")

	delete(stage2, "MessagesSize")

	delete(stage2, "PercentComplete")

	// stage 3, add additional properties values
	if len(stage2) > 0 {
		result := make(map[string]interface{})
		for k, v := range stage2 {
			var toadd interface{}
			if err := json.Unmarshal(v, &toadd); err != nil {
				return err
			}
			result[k] = toadd
		}
		m.HyperflexStPlatformClusterHealingInfoAO1P1 = result
	}

	return nil
}

// MarshalJSON marshals this object with additional properties into a JSON object
func (m HyperflexStPlatformClusterHealingInfoAO1P1) MarshalJSON() ([]byte, error) {
	var stage1 struct {

		// estimated completion time in seconds
		// Read Only: true
		EstimatedCompletionTimeInSeconds int64 `json:"EstimatedCompletionTimeInSeconds,omitempty"`

		// in progress
		// Read Only: true
		InProgress *bool `json:"InProgress,omitempty"`

		// messages
		// Read Only: true
		Messages []string `json:"Messages"`

		// messages iterator
		// Read Only: true
		MessagesIterator interface{} `json:"MessagesIterator,omitempty"`

		// messages size
		// Read Only: true
		MessagesSize int64 `json:"MessagesSize,omitempty"`

		// percent complete
		// Read Only: true
		PercentComplete int64 `json:"PercentComplete,omitempty"`
	}

	stage1.EstimatedCompletionTimeInSeconds = m.EstimatedCompletionTimeInSeconds

	stage1.InProgress = m.InProgress

	stage1.Messages = m.Messages

	stage1.MessagesIterator = m.MessagesIterator

	stage1.MessagesSize = m.MessagesSize

	stage1.PercentComplete = m.PercentComplete

	// make JSON object for known properties
	props, err := json.Marshal(stage1)
	if err != nil {
		return nil, err
	}

	if len(m.HyperflexStPlatformClusterHealingInfoAO1P1) == 0 {
		return props, nil
	}

	// make JSON object for the additional properties
	additional, err := json.Marshal(m.HyperflexStPlatformClusterHealingInfoAO1P1)
	if err != nil {
		return nil, err
	}

	if len(props) < 3 {
		return additional, nil
	}

	// concatenate the 2 objects
	props[len(props)-1] = ','
	return append(props, additional[1:]...), nil
}

// Validate validates this hyperflex st platform cluster healing info a o1 p1
func (m *HyperflexStPlatformClusterHealingInfoAO1P1) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HyperflexStPlatformClusterHealingInfoAO1P1) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HyperflexStPlatformClusterHealingInfoAO1P1) UnmarshalBinary(b []byte) error {
	var res HyperflexStPlatformClusterHealingInfoAO1P1
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
