// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// IamSecurityHolder Iam:Security Holder
//
// Holder for organization aggregated permissions and global account permissions.
// User configures permissions for entire account or subset of organizations and specifies associated roles with each organization.
// Intersight aggregates all the permissions and stores per organization aggregate permissions in iam.ResourcePermission object.
//
// swagger:model iamSecurityHolder
type IamSecurityHolder struct {
	MoBaseMo

	// A collection of references to the [iam.Account](mo://iam.Account) Managed Object.
	//
	// When this managed object is deleted, the referenced [iam.Account](mo://iam.Account) MO unsets its reference to this deleted MO.
	//
	// Read Only: true
	Account *IamAccountRef `json:"Account,omitempty"`

	// Per resource (organization) aggregate permissions and associated roles.
	//
	// Read Only: true
	ResourcePermissions []*IamResourcePermissionRef `json:"ResourcePermissions"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *IamSecurityHolder) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 MoBaseMo
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.MoBaseMo = aO0

	// AO1
	var dataAO1 struct {
		Account *IamAccountRef `json:"Account,omitempty"`

		ResourcePermissions []*IamResourcePermissionRef `json:"ResourcePermissions"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.Account = dataAO1.Account

	m.ResourcePermissions = dataAO1.ResourcePermissions

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m IamSecurityHolder) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.MoBaseMo)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	var dataAO1 struct {
		Account *IamAccountRef `json:"Account,omitempty"`

		ResourcePermissions []*IamResourcePermissionRef `json:"ResourcePermissions"`
	}

	dataAO1.Account = m.Account

	dataAO1.ResourcePermissions = m.ResourcePermissions

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this iam security holder
func (m *IamSecurityHolder) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with MoBaseMo
	if err := m.MoBaseMo.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAccount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResourcePermissions(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IamSecurityHolder) validateAccount(formats strfmt.Registry) error {

	if swag.IsZero(m.Account) { // not required
		return nil
	}

	if m.Account != nil {
		if err := m.Account.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Account")
			}
			return err
		}
	}

	return nil
}

func (m *IamSecurityHolder) validateResourcePermissions(formats strfmt.Registry) error {

	if swag.IsZero(m.ResourcePermissions) { // not required
		return nil
	}

	for i := 0; i < len(m.ResourcePermissions); i++ {
		if swag.IsZero(m.ResourcePermissions[i]) { // not required
			continue
		}

		if m.ResourcePermissions[i] != nil {
			if err := m.ResourcePermissions[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("ResourcePermissions" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *IamSecurityHolder) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IamSecurityHolder) UnmarshalBinary(b []byte) error {
	var res IamSecurityHolder
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
