// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// NiaapiApicCcoPost Niaapi:Apic Cco Post
//
// The post reporting a new release is available for APIC.
//
// swagger:model niaapiApicCcoPost
type NiaapiApicCcoPost struct {
	NiaapiNewReleasePost

	NiaapiApicCcoPostAllOf1
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *NiaapiApicCcoPost) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 NiaapiNewReleasePost
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.NiaapiNewReleasePost = aO0

	// AO1
	var aO1 NiaapiApicCcoPostAllOf1
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.NiaapiApicCcoPostAllOf1 = aO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m NiaapiApicCcoPost) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.NiaapiNewReleasePost)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.NiaapiApicCcoPostAllOf1)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this niaapi apic cco post
func (m *NiaapiApicCcoPost) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with NiaapiNewReleasePost
	if err := m.NiaapiNewReleasePost.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with NiaapiApicCcoPostAllOf1

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *NiaapiApicCcoPost) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NiaapiApicCcoPost) UnmarshalBinary(b []byte) error {
	var res NiaapiApicCcoPost
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// NiaapiApicCcoPostAllOf1 niaapi apic cco post all of1
// swagger:model NiaapiApicCcoPostAllOf1
type NiaapiApicCcoPostAllOf1 interface{}
