// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SnmpUser Snmp:User
//
// Complex type for a User based security model, for communication between an agent and manager. Applicable only for SNMPv3.
//
// swagger:model snmpUser
type SnmpUser struct {
	MoBaseComplexType

	SnmpUserAO1P1
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *SnmpUser) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 MoBaseComplexType
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.MoBaseComplexType = aO0

	// AO1
	var aO1 SnmpUserAO1P1
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.SnmpUserAO1P1 = aO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m SnmpUser) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.MoBaseComplexType)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.SnmpUserAO1P1)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this snmp user
func (m *SnmpUser) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with MoBaseComplexType
	if err := m.MoBaseComplexType.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with SnmpUserAO1P1
	if err := m.SnmpUserAO1P1.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *SnmpUser) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SnmpUser) UnmarshalBinary(b []byte) error {
	var res SnmpUser
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// SnmpUserAO1P1 snmp user a o1 p1
//
// swagger:model SnmpUserAO1P1
type SnmpUserAO1P1 struct {

	// Authorization password for the user.
	AuthPassword string `json:"AuthPassword,omitempty"`

	// Authorization protocol for authenticating the user.
	// Enum: [NA MD5 SHA]
	AuthType *string `json:"AuthType,omitempty"`

	// Indicates whether the value of the 'authPassword' property has been set.
	// Read Only: true
	IsAuthPasswordSet *bool `json:"IsAuthPasswordSet,omitempty"`

	// is privacy password set
	// Read Only: true
	IsPrivacyPasswordSet *bool `json:"IsPrivacyPasswordSet,omitempty"`

	// SNMP username. Must have a minimum of 1 and and a maximum of 31 characters.
	Name string `json:"Name,omitempty"`

	// Privacy password for the user.
	PrivacyPassword string `json:"PrivacyPassword,omitempty"`

	// Privacy protocol for the user.
	// Enum: [NA DES AES]
	PrivacyType *string `json:"PrivacyType,omitempty"`

	// Security mechanism used for communication between agent and manager.
	// Enum: [AuthPriv NoAuthNoPriv AuthNoPriv]
	SecurityLevel *string `json:"SecurityLevel,omitempty"`

	// snmp user a o1 p1
	SnmpUserAO1P1 map[string]interface{} `json:"-"`
}

// UnmarshalJSON unmarshals this object with additional properties from JSON
func (m *SnmpUserAO1P1) UnmarshalJSON(data []byte) error {
	// stage 1, bind the properties
	var stage1 struct {

		// Authorization password for the user.
		AuthPassword string `json:"AuthPassword,omitempty"`

		// Authorization protocol for authenticating the user.
		// Enum: [NA MD5 SHA]
		AuthType *string `json:"AuthType,omitempty"`

		// Indicates whether the value of the 'authPassword' property has been set.
		// Read Only: true
		IsAuthPasswordSet *bool `json:"IsAuthPasswordSet,omitempty"`

		// is privacy password set
		// Read Only: true
		IsPrivacyPasswordSet *bool `json:"IsPrivacyPasswordSet,omitempty"`

		// SNMP username. Must have a minimum of 1 and and a maximum of 31 characters.
		Name string `json:"Name,omitempty"`

		// Privacy password for the user.
		PrivacyPassword string `json:"PrivacyPassword,omitempty"`

		// Privacy protocol for the user.
		// Enum: [NA DES AES]
		PrivacyType *string `json:"PrivacyType,omitempty"`

		// Security mechanism used for communication between agent and manager.
		// Enum: [AuthPriv NoAuthNoPriv AuthNoPriv]
		SecurityLevel *string `json:"SecurityLevel,omitempty"`
	}
	if err := json.Unmarshal(data, &stage1); err != nil {
		return err
	}
	var rcv SnmpUserAO1P1

	rcv.AuthPassword = stage1.AuthPassword
	rcv.AuthType = stage1.AuthType
	rcv.IsAuthPasswordSet = stage1.IsAuthPasswordSet
	rcv.IsPrivacyPasswordSet = stage1.IsPrivacyPasswordSet
	rcv.Name = stage1.Name
	rcv.PrivacyPassword = stage1.PrivacyPassword
	rcv.PrivacyType = stage1.PrivacyType
	rcv.SecurityLevel = stage1.SecurityLevel
	*m = rcv

	// stage 2, remove properties and add to map
	stage2 := make(map[string]json.RawMessage)
	if err := json.Unmarshal(data, &stage2); err != nil {
		return err
	}

	delete(stage2, "AuthPassword")
	delete(stage2, "AuthType")
	delete(stage2, "IsAuthPasswordSet")
	delete(stage2, "IsPrivacyPasswordSet")
	delete(stage2, "Name")
	delete(stage2, "PrivacyPassword")
	delete(stage2, "PrivacyType")
	delete(stage2, "SecurityLevel")
	// stage 3, add additional properties values
	if len(stage2) > 0 {
		result := make(map[string]interface{})
		for k, v := range stage2 {
			var toadd interface{}
			if err := json.Unmarshal(v, &toadd); err != nil {
				return err
			}
			result[k] = toadd
		}
		m.SnmpUserAO1P1 = result
	}

	return nil
}

// MarshalJSON marshals this object with additional properties into a JSON object
func (m SnmpUserAO1P1) MarshalJSON() ([]byte, error) {
	var stage1 struct {

		// Authorization password for the user.
		AuthPassword string `json:"AuthPassword,omitempty"`

		// Authorization protocol for authenticating the user.
		// Enum: [NA MD5 SHA]
		AuthType *string `json:"AuthType,omitempty"`

		// Indicates whether the value of the 'authPassword' property has been set.
		// Read Only: true
		IsAuthPasswordSet *bool `json:"IsAuthPasswordSet,omitempty"`

		// is privacy password set
		// Read Only: true
		IsPrivacyPasswordSet *bool `json:"IsPrivacyPasswordSet,omitempty"`

		// SNMP username. Must have a minimum of 1 and and a maximum of 31 characters.
		Name string `json:"Name,omitempty"`

		// Privacy password for the user.
		PrivacyPassword string `json:"PrivacyPassword,omitempty"`

		// Privacy protocol for the user.
		// Enum: [NA DES AES]
		PrivacyType *string `json:"PrivacyType,omitempty"`

		// Security mechanism used for communication between agent and manager.
		// Enum: [AuthPriv NoAuthNoPriv AuthNoPriv]
		SecurityLevel *string `json:"SecurityLevel,omitempty"`
	}

	stage1.AuthPassword = m.AuthPassword
	stage1.AuthType = m.AuthType
	stage1.IsAuthPasswordSet = m.IsAuthPasswordSet
	stage1.IsPrivacyPasswordSet = m.IsPrivacyPasswordSet
	stage1.Name = m.Name
	stage1.PrivacyPassword = m.PrivacyPassword
	stage1.PrivacyType = m.PrivacyType
	stage1.SecurityLevel = m.SecurityLevel

	// make JSON object for known properties
	props, err := json.Marshal(stage1)
	if err != nil {
		return nil, err
	}

	if len(m.SnmpUserAO1P1) == 0 {
		return props, nil
	}

	// make JSON object for the additional properties
	additional, err := json.Marshal(m.SnmpUserAO1P1)
	if err != nil {
		return nil, err
	}

	if len(props) < 3 {
		return additional, nil
	}

	// concatenate the 2 objects
	props[len(props)-1] = ','
	return append(props, additional[1:]...), nil
}

// Validate validates this snmp user a o1 p1
func (m *SnmpUserAO1P1) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAuthType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePrivacyType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSecurityLevel(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var snmpUserAO1P1TypeAuthTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["NA","MD5","SHA"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		snmpUserAO1P1TypeAuthTypePropEnum = append(snmpUserAO1P1TypeAuthTypePropEnum, v)
	}
}

const (

	// SnmpUserAO1P1AuthTypeNA captures enum value "NA"
	SnmpUserAO1P1AuthTypeNA string = "NA"

	// SnmpUserAO1P1AuthTypeMD5 captures enum value "MD5"
	SnmpUserAO1P1AuthTypeMD5 string = "MD5"

	// SnmpUserAO1P1AuthTypeSHA captures enum value "SHA"
	SnmpUserAO1P1AuthTypeSHA string = "SHA"
)

// prop value enum
func (m *SnmpUserAO1P1) validateAuthTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, snmpUserAO1P1TypeAuthTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *SnmpUserAO1P1) validateAuthType(formats strfmt.Registry) error {

	if swag.IsZero(m.AuthType) { // not required
		return nil
	}

	// value enum
	if err := m.validateAuthTypeEnum("AuthType", "body", *m.AuthType); err != nil {
		return err
	}

	return nil
}

var snmpUserAO1P1TypePrivacyTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["NA","DES","AES"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		snmpUserAO1P1TypePrivacyTypePropEnum = append(snmpUserAO1P1TypePrivacyTypePropEnum, v)
	}
}

const (

	// SnmpUserAO1P1PrivacyTypeNA captures enum value "NA"
	SnmpUserAO1P1PrivacyTypeNA string = "NA"

	// SnmpUserAO1P1PrivacyTypeDES captures enum value "DES"
	SnmpUserAO1P1PrivacyTypeDES string = "DES"

	// SnmpUserAO1P1PrivacyTypeAES captures enum value "AES"
	SnmpUserAO1P1PrivacyTypeAES string = "AES"
)

// prop value enum
func (m *SnmpUserAO1P1) validatePrivacyTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, snmpUserAO1P1TypePrivacyTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *SnmpUserAO1P1) validatePrivacyType(formats strfmt.Registry) error {

	if swag.IsZero(m.PrivacyType) { // not required
		return nil
	}

	// value enum
	if err := m.validatePrivacyTypeEnum("PrivacyType", "body", *m.PrivacyType); err != nil {
		return err
	}

	return nil
}

var snmpUserAO1P1TypeSecurityLevelPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["AuthPriv","NoAuthNoPriv","AuthNoPriv"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		snmpUserAO1P1TypeSecurityLevelPropEnum = append(snmpUserAO1P1TypeSecurityLevelPropEnum, v)
	}
}

const (

	// SnmpUserAO1P1SecurityLevelAuthPriv captures enum value "AuthPriv"
	SnmpUserAO1P1SecurityLevelAuthPriv string = "AuthPriv"

	// SnmpUserAO1P1SecurityLevelNoAuthNoPriv captures enum value "NoAuthNoPriv"
	SnmpUserAO1P1SecurityLevelNoAuthNoPriv string = "NoAuthNoPriv"

	// SnmpUserAO1P1SecurityLevelAuthNoPriv captures enum value "AuthNoPriv"
	SnmpUserAO1P1SecurityLevelAuthNoPriv string = "AuthNoPriv"
)

// prop value enum
func (m *SnmpUserAO1P1) validateSecurityLevelEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, snmpUserAO1P1TypeSecurityLevelPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *SnmpUserAO1P1) validateSecurityLevel(formats strfmt.Registry) error {

	if swag.IsZero(m.SecurityLevel) { // not required
		return nil
	}

	// value enum
	if err := m.validateSecurityLevelEnum("SecurityLevel", "body", *m.SecurityLevel); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SnmpUserAO1P1) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SnmpUserAO1P1) UnmarshalBinary(b []byte) error {
	var res SnmpUserAO1P1
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
