// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// SoftwarerepositoryFileServer Softwarerepository:File Server
//
// An external software repository which serves as the source of the file to be imported into the image catalog. If the source is the user's local machine, the file is copied/imported into Intersight's local repository. If not, only a pointer to the file in the external repository is created in the image catalog.
// For more information, please refer to the softwarerepositoryUploader and softwarerepositoryFile object descriptions where this type is used.
//
// swagger:model softwarerepositoryFileServer
type SoftwarerepositoryFileServer struct {
	MoBaseComplexType

	// a o1
	AO1 map[string]interface{} `json:"-"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *SoftwarerepositoryFileServer) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 MoBaseComplexType
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.MoBaseComplexType = aO0

	// AO1
	var aO1 map[string]interface{}
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.AO1 = aO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m SoftwarerepositoryFileServer) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.MoBaseComplexType)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.AO1)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this softwarerepository file server
func (m *SoftwarerepositoryFileServer) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with MoBaseComplexType
	if err := m.MoBaseComplexType.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with map[string]interface{}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *SoftwarerepositoryFileServer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SoftwarerepositoryFileServer) UnmarshalBinary(b []byte) error {
	var res SoftwarerepositoryFileServer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
