// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// StorageHost Storage:Host
//
// Generic storage host object. It is a logical object to associate initiators to expose volume as LUN.
//
// swagger:model storageHost
type StorageHost struct {
	MoBaseMo

	// Short description about the host.
	//
	// Read Only: true
	Description string `json:"Description,omitempty"`

	// List of initiators which are associated with host.
	//
	// Read Only: true
	Initiators []*StorageInitiator `json:"Initiators"`

	// Name of the host in storage array.
	//
	// Read Only: true
	Name string `json:"Name,omitempty"`

	// Operating system running on the host.
	//
	// Read Only: true
	OsType string `json:"OsType,omitempty"`

	// Storage array managed object.
	//
	// Read Only: true
	StorageArray *StorageGenericArrayRef `json:"StorageArray,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *StorageHost) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 MoBaseMo
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.MoBaseMo = aO0

	// AO1
	var dataAO1 struct {
		Description string `json:"Description,omitempty"`

		Initiators []*StorageInitiator `json:"Initiators"`

		Name string `json:"Name,omitempty"`

		OsType string `json:"OsType,omitempty"`

		StorageArray *StorageGenericArrayRef `json:"StorageArray,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.Description = dataAO1.Description

	m.Initiators = dataAO1.Initiators

	m.Name = dataAO1.Name

	m.OsType = dataAO1.OsType

	m.StorageArray = dataAO1.StorageArray

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m StorageHost) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.MoBaseMo)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	var dataAO1 struct {
		Description string `json:"Description,omitempty"`

		Initiators []*StorageInitiator `json:"Initiators"`

		Name string `json:"Name,omitempty"`

		OsType string `json:"OsType,omitempty"`

		StorageArray *StorageGenericArrayRef `json:"StorageArray,omitempty"`
	}

	dataAO1.Description = m.Description

	dataAO1.Initiators = m.Initiators

	dataAO1.Name = m.Name

	dataAO1.OsType = m.OsType

	dataAO1.StorageArray = m.StorageArray

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this storage host
func (m *StorageHost) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with MoBaseMo
	if err := m.MoBaseMo.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInitiators(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStorageArray(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *StorageHost) validateInitiators(formats strfmt.Registry) error {

	if swag.IsZero(m.Initiators) { // not required
		return nil
	}

	for i := 0; i < len(m.Initiators); i++ {
		if swag.IsZero(m.Initiators[i]) { // not required
			continue
		}

		if m.Initiators[i] != nil {
			if err := m.Initiators[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Initiators" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *StorageHost) validateStorageArray(formats strfmt.Registry) error {

	if swag.IsZero(m.StorageArray) { // not required
		return nil
	}

	if m.StorageArray != nil {
		if err := m.StorageArray.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("StorageArray")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *StorageHost) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StorageHost) UnmarshalBinary(b []byte) error {
	var res StorageHost
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
