// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// StorageFlexFlashPhysicalDrive Storage:Flex Flash Physical Drive
//
// Physical Drive repersenting a SD Card.
//
// swagger:model storageFlexFlashPhysicalDrive
type StorageFlexFlashPhysicalDrive struct {
	EquipmentBase

	// card status
	CardStatus string `json:"CardStatus,omitempty"`

	// card type
	CardType string `json:"CardType,omitempty"`

	// oem Id
	OemID string `json:"OemId,omitempty"`

	// pd status
	PdStatus string `json:"PdStatus,omitempty"`

	// The Device to which this Managed Object is associated.
	//
	// Read Only: true
	RegisteredDevice *AssetDeviceRegistrationRef `json:"RegisteredDevice,omitempty"`

	// A collection of references to the [storage.FlexFlashController](mo://storage.FlexFlashController) Managed Object.
	//
	// When this managed object is deleted, the referenced [storage.FlexFlashController](mo://storage.FlexFlashController) MO unsets its reference to this deleted MO.
	//
	// Read Only: true
	StorageFlexFlashController *StorageFlexFlashControllerRef `json:"StorageFlexFlashController,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *StorageFlexFlashPhysicalDrive) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 EquipmentBase
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.EquipmentBase = aO0

	// AO1
	var dataAO1 struct {
		CardStatus string `json:"CardStatus,omitempty"`

		CardType string `json:"CardType,omitempty"`

		OemID string `json:"OemId,omitempty"`

		PdStatus string `json:"PdStatus,omitempty"`

		RegisteredDevice *AssetDeviceRegistrationRef `json:"RegisteredDevice,omitempty"`

		StorageFlexFlashController *StorageFlexFlashControllerRef `json:"StorageFlexFlashController,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.CardStatus = dataAO1.CardStatus

	m.CardType = dataAO1.CardType

	m.OemID = dataAO1.OemID

	m.PdStatus = dataAO1.PdStatus

	m.RegisteredDevice = dataAO1.RegisteredDevice

	m.StorageFlexFlashController = dataAO1.StorageFlexFlashController

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m StorageFlexFlashPhysicalDrive) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.EquipmentBase)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	var dataAO1 struct {
		CardStatus string `json:"CardStatus,omitempty"`

		CardType string `json:"CardType,omitempty"`

		OemID string `json:"OemId,omitempty"`

		PdStatus string `json:"PdStatus,omitempty"`

		RegisteredDevice *AssetDeviceRegistrationRef `json:"RegisteredDevice,omitempty"`

		StorageFlexFlashController *StorageFlexFlashControllerRef `json:"StorageFlexFlashController,omitempty"`
	}

	dataAO1.CardStatus = m.CardStatus

	dataAO1.CardType = m.CardType

	dataAO1.OemID = m.OemID

	dataAO1.PdStatus = m.PdStatus

	dataAO1.RegisteredDevice = m.RegisteredDevice

	dataAO1.StorageFlexFlashController = m.StorageFlexFlashController

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this storage flex flash physical drive
func (m *StorageFlexFlashPhysicalDrive) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with EquipmentBase
	if err := m.EquipmentBase.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRegisteredDevice(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStorageFlexFlashController(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *StorageFlexFlashPhysicalDrive) validateRegisteredDevice(formats strfmt.Registry) error {

	if swag.IsZero(m.RegisteredDevice) { // not required
		return nil
	}

	if m.RegisteredDevice != nil {
		if err := m.RegisteredDevice.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("RegisteredDevice")
			}
			return err
		}
	}

	return nil
}

func (m *StorageFlexFlashPhysicalDrive) validateStorageFlexFlashController(formats strfmt.Registry) error {

	if swag.IsZero(m.StorageFlexFlashController) { // not required
		return nil
	}

	if m.StorageFlexFlashController != nil {
		if err := m.StorageFlexFlashController.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("StorageFlexFlashController")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *StorageFlexFlashPhysicalDrive) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StorageFlexFlashPhysicalDrive) UnmarshalBinary(b []byte) error {
	var res StorageFlexFlashPhysicalDrive
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
