// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// SyslogLocalFileLoggingClient Local Client
//
// Local logging client on the endpoint.
//
// swagger:model syslogLocalFileLoggingClient
type SyslogLocalFileLoggingClient struct {
	SyslogLocalClientBase

	SyslogLocalFileLoggingClientAllOf1
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *SyslogLocalFileLoggingClient) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 SyslogLocalClientBase
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.SyslogLocalClientBase = aO0

	// AO1
	var aO1 SyslogLocalFileLoggingClientAllOf1
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.SyslogLocalFileLoggingClientAllOf1 = aO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m SyslogLocalFileLoggingClient) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.SyslogLocalClientBase)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.SyslogLocalFileLoggingClientAllOf1)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this syslog local file logging client
func (m *SyslogLocalFileLoggingClient) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with SyslogLocalClientBase
	if err := m.SyslogLocalClientBase.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with SyslogLocalFileLoggingClientAllOf1

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *SyslogLocalFileLoggingClient) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SyslogLocalFileLoggingClient) UnmarshalBinary(b []byte) error {
	var res SyslogLocalFileLoggingClient
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// SyslogLocalFileLoggingClientAllOf1 syslog local file logging client all of1
// swagger:model SyslogLocalFileLoggingClientAllOf1
type SyslogLocalFileLoggingClientAllOf1 interface{}
