// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// VnicRoceSettings RoCE Settings
//
// Settings for RDMA over Converged Ethernet.
//
// swagger:model vnicRoceSettings
type VnicRoceSettings struct {
	VnicRoceSettingsAO0P0
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *VnicRoceSettings) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 VnicRoceSettingsAO0P0
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.VnicRoceSettingsAO0P0 = aO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m VnicRoceSettings) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	aO0, err := swag.WriteJSON(m.VnicRoceSettingsAO0P0)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this vnic roce settings
func (m *VnicRoceSettings) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with VnicRoceSettingsAO0P0
	if err := m.VnicRoceSettingsAO0P0.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *VnicRoceSettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VnicRoceSettings) UnmarshalBinary(b []byte) error {
	var res VnicRoceSettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// VnicRoceSettingsAO0P0 vnic roce settings a o0 p0
// swagger:model VnicRoceSettingsAO0P0
type VnicRoceSettingsAO0P0 struct {

	// If enabled sets RDMA over Converged Ethernet (RoCE) on this virtual interface.
	//
	Enabled *bool `json:"Enabled,omitempty"`

	// The number of memory regions per adapter. Recommended value = integer power of 2.
	//
	MemoryRegions int64 `json:"MemoryRegions,omitempty"`

	// The concrete type of this complex type.
	//
	// The ObjectType property must be set explicitly by API clients when the type is ambiguous. In all other cases, the
	// ObjectType is optional.
	// The type is ambiguous when a managed object contains an array of nested documents, and the documents in the array
	// are heterogeneous, i.e. the array can contain nested documents of different types.
	//
	//
	ObjectType string `json:"ObjectType,omitempty"`

	// The number of queue pairs per adapter. Recommended value = integer power of 2.
	//
	QueuePairs int64 `json:"QueuePairs,omitempty"`

	// The number of resource groups per adapter. Recommended value = be an integer power of 2 greater than or equal to the number of CPU cores on the system for optimum performance.
	//
	ResourceGroups int64 `json:"ResourceGroups,omitempty"`

	// vnic roce settings a o0 p0
	VnicRoceSettingsAO0P0 map[string]interface{} `json:"-"`
}

// UnmarshalJSON unmarshals this object with additional properties from JSON
func (m *VnicRoceSettingsAO0P0) UnmarshalJSON(data []byte) error {
	// stage 1, bind the properties
	var stage1 struct {

		// If enabled sets RDMA over Converged Ethernet (RoCE) on this virtual interface.
		//
		Enabled *bool `json:"Enabled,omitempty"`

		// The number of memory regions per adapter. Recommended value = integer power of 2.
		//
		MemoryRegions int64 `json:"MemoryRegions,omitempty"`

		// The concrete type of this complex type.
		//
		// The ObjectType property must be set explicitly by API clients when the type is ambiguous. In all other cases, the
		// ObjectType is optional.
		// The type is ambiguous when a managed object contains an array of nested documents, and the documents in the array
		// are heterogeneous, i.e. the array can contain nested documents of different types.
		//
		//
		ObjectType string `json:"ObjectType,omitempty"`

		// The number of queue pairs per adapter. Recommended value = integer power of 2.
		//
		QueuePairs int64 `json:"QueuePairs,omitempty"`

		// The number of resource groups per adapter. Recommended value = be an integer power of 2 greater than or equal to the number of CPU cores on the system for optimum performance.
		//
		ResourceGroups int64 `json:"ResourceGroups,omitempty"`
	}
	if err := json.Unmarshal(data, &stage1); err != nil {
		return err
	}
	var rcv VnicRoceSettingsAO0P0

	rcv.Enabled = stage1.Enabled

	rcv.MemoryRegions = stage1.MemoryRegions

	rcv.ObjectType = stage1.ObjectType

	rcv.QueuePairs = stage1.QueuePairs

	rcv.ResourceGroups = stage1.ResourceGroups

	*m = rcv

	// stage 2, remove properties and add to map
	stage2 := make(map[string]json.RawMessage)
	if err := json.Unmarshal(data, &stage2); err != nil {
		return err
	}

	delete(stage2, "Enabled")

	delete(stage2, "MemoryRegions")

	delete(stage2, "ObjectType")

	delete(stage2, "QueuePairs")

	delete(stage2, "ResourceGroups")

	// stage 3, add additional properties values
	if len(stage2) > 0 {
		result := make(map[string]interface{})
		for k, v := range stage2 {
			var toadd interface{}
			if err := json.Unmarshal(v, &toadd); err != nil {
				return err
			}
			result[k] = toadd
		}
		m.VnicRoceSettingsAO0P0 = result
	}

	return nil
}

// MarshalJSON marshals this object with additional properties into a JSON object
func (m VnicRoceSettingsAO0P0) MarshalJSON() ([]byte, error) {
	var stage1 struct {

		// If enabled sets RDMA over Converged Ethernet (RoCE) on this virtual interface.
		//
		Enabled *bool `json:"Enabled,omitempty"`

		// The number of memory regions per adapter. Recommended value = integer power of 2.
		//
		MemoryRegions int64 `json:"MemoryRegions,omitempty"`

		// The concrete type of this complex type.
		//
		// The ObjectType property must be set explicitly by API clients when the type is ambiguous. In all other cases, the
		// ObjectType is optional.
		// The type is ambiguous when a managed object contains an array of nested documents, and the documents in the array
		// are heterogeneous, i.e. the array can contain nested documents of different types.
		//
		//
		ObjectType string `json:"ObjectType,omitempty"`

		// The number of queue pairs per adapter. Recommended value = integer power of 2.
		//
		QueuePairs int64 `json:"QueuePairs,omitempty"`

		// The number of resource groups per adapter. Recommended value = be an integer power of 2 greater than or equal to the number of CPU cores on the system for optimum performance.
		//
		ResourceGroups int64 `json:"ResourceGroups,omitempty"`
	}

	stage1.Enabled = m.Enabled

	stage1.MemoryRegions = m.MemoryRegions

	stage1.ObjectType = m.ObjectType

	stage1.QueuePairs = m.QueuePairs

	stage1.ResourceGroups = m.ResourceGroups

	// make JSON object for known properties
	props, err := json.Marshal(stage1)
	if err != nil {
		return nil, err
	}

	if len(m.VnicRoceSettingsAO0P0) == 0 {
		return props, nil
	}

	// make JSON object for the additional properties
	additional, err := json.Marshal(m.VnicRoceSettingsAO0P0)
	if err != nil {
		return nil, err
	}

	if len(props) < 3 {
		return additional, nil
	}

	// concatenate the 2 objects
	props[len(props)-1] = ','
	return append(props, additional[1:]...), nil
}

// Validate validates this vnic roce settings a o0 p0
func (m *VnicRoceSettingsAO0P0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VnicRoceSettingsAO0P0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VnicRoceSettingsAO0P0) UnmarshalBinary(b []byte) error {
	var res VnicRoceSettingsAO0P0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
