// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// VnicUsnicSettings USNIC Settings
//
// User Space NIC Settings that enable low-latency and higher throughput by bypassing the kernel layer when sending/receiving packets.
//
// swagger:model vnicUsnicSettings
type VnicUsnicSettings struct {
	MoBaseComplexType

	VnicUsnicSettingsAO1P1
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *VnicUsnicSettings) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 MoBaseComplexType
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.MoBaseComplexType = aO0

	// AO1
	var aO1 VnicUsnicSettingsAO1P1
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.VnicUsnicSettingsAO1P1 = aO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m VnicUsnicSettings) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.MoBaseComplexType)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.VnicUsnicSettingsAO1P1)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this vnic usnic settings
func (m *VnicUsnicSettings) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with MoBaseComplexType
	if err := m.MoBaseComplexType.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with VnicUsnicSettingsAO1P1
	if err := m.VnicUsnicSettingsAO1P1.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *VnicUsnicSettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VnicUsnicSettings) UnmarshalBinary(b []byte) error {
	var res VnicUsnicSettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// VnicUsnicSettingsAO1P1 vnic usnic settings a o1 p1
// swagger:model VnicUsnicSettingsAO1P1
type VnicUsnicSettingsAO1P1 struct {

	// Class of Service to be used for traffic on the usNIC.
	//
	Cos int64 `json:"Cos,omitempty"`

	// Number of usNIC interfaces to be created.
	//
	Count int64 `json:"Count,omitempty"`

	// Ethernet Adapter policy to be associated with the usNICs.
	//
	UsnicAdapterPolicy string `json:"UsnicAdapterPolicy,omitempty"`

	// vnic usnic settings a o1 p1
	VnicUsnicSettingsAO1P1 map[string]interface{} `json:"-"`
}

// UnmarshalJSON unmarshals this object with additional properties from JSON
func (m *VnicUsnicSettingsAO1P1) UnmarshalJSON(data []byte) error {
	// stage 1, bind the properties
	var stage1 struct {

		// Class of Service to be used for traffic on the usNIC.
		//
		Cos int64 `json:"Cos,omitempty"`

		// Number of usNIC interfaces to be created.
		//
		Count int64 `json:"Count,omitempty"`

		// Ethernet Adapter policy to be associated with the usNICs.
		//
		UsnicAdapterPolicy string `json:"UsnicAdapterPolicy,omitempty"`
	}
	if err := json.Unmarshal(data, &stage1); err != nil {
		return err
	}
	var rcv VnicUsnicSettingsAO1P1

	rcv.Cos = stage1.Cos

	rcv.Count = stage1.Count

	rcv.UsnicAdapterPolicy = stage1.UsnicAdapterPolicy

	*m = rcv

	// stage 2, remove properties and add to map
	stage2 := make(map[string]json.RawMessage)
	if err := json.Unmarshal(data, &stage2); err != nil {
		return err
	}

	delete(stage2, "Cos")

	delete(stage2, "Count")

	delete(stage2, "UsnicAdapterPolicy")

	// stage 3, add additional properties values
	if len(stage2) > 0 {
		result := make(map[string]interface{})
		for k, v := range stage2 {
			var toadd interface{}
			if err := json.Unmarshal(v, &toadd); err != nil {
				return err
			}
			result[k] = toadd
		}
		m.VnicUsnicSettingsAO1P1 = result
	}

	return nil
}

// MarshalJSON marshals this object with additional properties into a JSON object
func (m VnicUsnicSettingsAO1P1) MarshalJSON() ([]byte, error) {
	var stage1 struct {

		// Class of Service to be used for traffic on the usNIC.
		//
		Cos int64 `json:"Cos,omitempty"`

		// Number of usNIC interfaces to be created.
		//
		Count int64 `json:"Count,omitempty"`

		// Ethernet Adapter policy to be associated with the usNICs.
		//
		UsnicAdapterPolicy string `json:"UsnicAdapterPolicy,omitempty"`
	}

	stage1.Cos = m.Cos

	stage1.Count = m.Count

	stage1.UsnicAdapterPolicy = m.UsnicAdapterPolicy

	// make JSON object for known properties
	props, err := json.Marshal(stage1)
	if err != nil {
		return nil, err
	}

	if len(m.VnicUsnicSettingsAO1P1) == 0 {
		return props, nil
	}

	// make JSON object for the additional properties
	additional, err := json.Marshal(m.VnicUsnicSettingsAO1P1)
	if err != nil {
		return nil, err
	}

	if len(props) < 3 {
		return additional, nil
	}

	// concatenate the 2 objects
	props[len(props)-1] = ','
	return append(props, additional[1:]...), nil
}

// Validate validates this vnic usnic settings a o1 p1
func (m *VnicUsnicSettingsAO1P1) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VnicUsnicSettingsAO1P1) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VnicUsnicSettingsAO1P1) UnmarshalBinary(b []byte) error {
	var res VnicUsnicSettingsAO1P1
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
